/*
 * KIP-17 API
 *   # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1100050 | incorrect request 1100101 | data don't exist 1100251 | its value is out of range; size 1104401 | failed to get an account |   ## 404: Not Found   | Code | Messages |   | --- | --- |   | 1104404 | Token not found |   ## 409: Conflict   | Code | Messages |   | --- | --- |   | 1104400 | Duplicate alias - test |  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xyz.groundx.caver_ext_kas.rest_client.io.swagger.client.api.kip17.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TransferKip17TokenRequest
 */


public class TransferKip17TokenRequest {
  @SerializedName("sender")
  private String sender = null;

  @SerializedName("owner")
  private String owner = null;

  @SerializedName("to")
  private String to = null;

  public TransferKip17TokenRequest sender(String sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Sender EOA address
   * @return sender
  **/
  @Schema(example = "0x9eaf20b40e0f1ced5dbba6f5cfb0d3e12b0534f4", required = true, description = "Sender EOA address")
  public String getSender() {
    return sender;
  }

  public void setSender(String sender) {
    this.sender = sender;
  }

  public TransferKip17TokenRequest owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Owner EOA address
   * @return owner
  **/
  @Schema(example = "0x9eaf20b40e0f1ced5dbba6f5cfb0d3e12b0534f4", required = true, description = "Owner EOA address")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public TransferKip17TokenRequest to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Recipient EOA address
   * @return to
  **/
  @Schema(example = "0xDc277E2D89b92336A4ee80be3c7142443FDaDE47", required = true, description = "Recipient EOA address")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferKip17TokenRequest transferKip17TokenRequest = (TransferKip17TokenRequest) o;
    return Objects.equals(this.sender, transferKip17TokenRequest.sender) &&
        Objects.equals(this.owner, transferKip17TokenRequest.owner) &&
        Objects.equals(this.to, transferKip17TokenRequest.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sender, owner, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferKip17TokenRequest {\n");
    
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
