/*
 * Token History API
 * # Introduction  Token History API allows you to query the transaction history of KLAY, FTs (KIP-7 and Labelled ERC-20), NFTs (KIP-17 and Labelled ERC-721), and MTs (KIP-37 and Labelled ERC-1155). You can track KLAY's transaction history or retrieve NFT-related data of a certain EOA.   For more details on using Token History API, please refer to the [Tutorial](https://docs.klaytnapi.com/tutorial).   For any inquiries on this document or KAS in general, please visit [Developer Forum](https://forum.klaytn.com/).  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xyz.groundx.caver_ext_kas.rest_client.io.swagger.client.api.tokenhistory.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Transaction
 */


public class Transaction {
  @SerializedName("feePayer")
  private String feePayer = null;

  @SerializedName("feeRatio")
  private Integer feeRatio = null;

  @SerializedName("fee")
  private String fee = null;

  @SerializedName("from")
  private String from = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  @SerializedName("transactionHash")
  private String transactionHash = null;

  @SerializedName("blockNumber")
  private Long blockNumber = null;

  @SerializedName("typeInt")
  private Integer typeInt = null;

  @SerializedName("value")
  private String value = null;

  public Transaction feePayer(String feePayer) {
    this.feePayer = feePayer;
    return this;
  }

   /**
   * Fee delegation account address (20-byte)
   * @return feePayer
  **/
  @Schema(example = "1192693860661700396879673921856029630237486527498", required = true, description = "Fee delegation account address (20-byte)")
  public String getFeePayer() {
    return feePayer;
  }

  public void setFeePayer(String feePayer) {
    this.feePayer = feePayer;
  }

  public Transaction feeRatio(Integer feeRatio) {
    this.feeRatio = feeRatio;
    return this;
  }

   /**
   * Fee delegation ratio
   * @return feeRatio
  **/
  @Schema(example = "100", required = true, description = "Fee delegation ratio")
  public Integer getFeeRatio() {
    return feeRatio;
  }

  public void setFeeRatio(Integer feeRatio) {
    this.feeRatio = feeRatio;
  }

  public Transaction fee(String fee) {
    this.fee = fee;
    return this;
  }

   /**
   * Gas fee
   * @return fee
  **/
  @Schema(example = "42069", required = true, description = "Gas fee")
  public String getFee() {
    return fee;
  }

  public void setFee(String fee) {
    this.fee = fee;
  }

  public Transaction from(String from) {
    this.from = from;
    return this;
  }

   /**
   * EOA of the sender of transaction (20-byte)
   * @return from
  **/
  @Schema(example = "538243955260495079143208573429421427237585534683", required = true, description = "EOA of the sender of transaction (20-byte)")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public Transaction timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Time of transaction (timestamp)
   * @return timestamp
  **/
  @Schema(example = "1592180992", required = true, description = "Time of transaction (timestamp)")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public Transaction transactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Transaction hash (32-byte)
   * @return transactionHash
  **/
  @Schema(example = "88941640552803633154072611475047379401865108829661485995735632343373081359608", required = true, description = "Transaction hash (32-byte)")
  public String getTransactionHash() {
    return transactionHash;
  }

  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }

  public Transaction blockNumber(Long blockNumber) {
    this.blockNumber = blockNumber;
    return this;
  }

   /**
   * Number of the block with the transaction
   * @return blockNumber
  **/
  @Schema(example = "5312105", required = true, description = "Number of the block with the transaction")
  public Long getBlockNumber() {
    return blockNumber;
  }

  public void setBlockNumber(Long blockNumber) {
    this.blockNumber = blockNumber;
  }

  public Transaction typeInt(Integer typeInt) {
    this.typeInt = typeInt;
    return this;
  }

   /**
   * Transaction type
   * @return typeInt
  **/
  @Schema(example = "10", required = true, description = "Transaction type")
  public Integer getTypeInt() {
    return typeInt;
  }

  public void setTypeInt(Integer typeInt) {
    this.typeInt = typeInt;
  }

  public Transaction value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Amount of KLAY transferred (in hexadecimal)
   * @return value
  **/
  @Schema(example = "10", required = true, description = "Amount of KLAY transferred (in hexadecimal)")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.feePayer, transaction.feePayer) &&
        Objects.equals(this.feeRatio, transaction.feeRatio) &&
        Objects.equals(this.fee, transaction.fee) &&
        Objects.equals(this.from, transaction.from) &&
        Objects.equals(this.timestamp, transaction.timestamp) &&
        Objects.equals(this.transactionHash, transaction.transactionHash) &&
        Objects.equals(this.blockNumber, transaction.blockNumber) &&
        Objects.equals(this.typeInt, transaction.typeInt) &&
        Objects.equals(this.value, transaction.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feePayer, feeRatio, fee, from, timestamp, transactionHash, blockNumber, typeInt, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    feePayer: ").append(toIndentedString(feePayer)).append("\n");
    sb.append("    feeRatio: ").append(toIndentedString(feeRatio)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n");
    sb.append("    typeInt: ").append(toIndentedString(typeInt)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
