/*
 * Anchor API
 * # Introduction 이 문서는 KAS\\(Klaytn API Service\\)의 Anchor API를 소개하는 문서입니다. Anchor API는 서비스 체인 데이터의 신뢰성을 보장하기 위해 데이터 신뢰성을 증명할 수 있는 메타데이터를 Klaytn 메인 체인에 전송하는 기능을 제공합니다.  자세한 사용 예시는 [튜토리얼](링크)를 확인하십시오.    # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1071010 | data don't exist 1072100 | same payload ID or payload was already anchored 1072101 | all configured accounts have insufficient funds |  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api.anchor.v1.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * 오퍼레이터 정보
 */
@Schema(description = "오퍼레이터 정보")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-25T06:25:39.655Z[GMT]")
public class Operator {
  @SerializedName("createdAt")
  private Long createdAt = null;

  @SerializedName("operator")
  private String operator = null;

  @SerializedName("setting")
  private OperatorSetting setting = null;

  public Operator createdAt(Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 오퍼레이터 생성 시간
   * @return createdAt
  **/
  @Schema(example = "1600156363", required = true, description = "오퍼레이터 생성 시간")
  public Long getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }

  public Operator operator(String operator) {
    this.operator = operator;
    return this;
  }

   /**
   * 오퍼레이터 클레이튼 계정 주소
   * @return operator
  **/
  @Schema(example = "0x36C144b998FbEF7faf092b01815194a18e1a1163", required = true, description = "오퍼레이터 클레이튼 계정 주소")
  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }

  public Operator setting(OperatorSetting setting) {
    this.setting = setting;
    return this;
  }

   /**
   * Get setting
   * @return setting
  **/
  @Schema(description = "")
  public OperatorSetting getSetting() {
    return setting;
  }

  public void setSetting(OperatorSetting setting) {
    this.setting = setting;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Operator operator = (Operator) o;
    return Objects.equals(this.createdAt, operator.createdAt) &&
        Objects.equals(this.operator, operator.operator) &&
        Objects.equals(this.setting, operator.setting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, operator, setting);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Operator {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    setting: ").append(toIndentedString(setting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
